from .task import Task
from .approval import Approval
from .bazargani_lead import LeadInfo
from .crm_num import CRMNum
from .crm_entry import CRMEntry
from .department import Department
from .lead import Lead
from .notification import Notification
from .person import Person
from .sales import Sale
from .salespersonreport import SalesPersonReport
from .tag import Tag
from .task_report import TaskReport
