# Generated by Django 5.0.2 on 2024-08-10 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conf', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approval',
            name='person',
        ),
        migrations.DeleteModel(
            name='CRMEntry',
        ),
        migrations.RemoveField(
            model_name='crmnum',
            name='person',
        ),
        migrations.RemoveField(
            model_name='person',
            name='department',
        ),
        migrations.DeleteModel(
            name='Lead',
        ),
        migrations.DeleteModel(
            name='LeadInfo',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='person',
        ),
        migrations.RemoveField(
            model_name='person',
            name='user',
        ),
        migrations.RemoveField(
            model_name='salespersonreport',
            name='person',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='person',
        ),
        migrations.RemoveField(
            model_name='task',
            name='person',
        ),
        migrations.RemoveField(
            model_name='task',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='task',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='task',
            name='assigned_by',
        ),
        migrations.RemoveField(
            model_name='task',
            name='team_members',
        ),
        migrations.DeleteModel(
            name='TaskReport',
        ),
        migrations.DeleteModel(
            name='Approval',
        ),
        migrations.DeleteModel(
            name='CRMNum',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='SalesPersonReport',
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
